### ISSUE TITLE
Замечания лаб1 @Kerpee

### ISSUE THREAD

**Issue by ananasn** [Kerpee/Lab1#1]
Замечания указанные ниже нужно исправить @Kerpee 

1. Не нужно писать комментарии для каждой строчки, сам код должен быть читаемым и понятным. Этому способствует оформление по PEP8 и осознанное название всех переменных (где название отражает смысл того, что в ней хранится).
2. Код оформлен не по PEP8. Обратите внимание как операторы должны обрамляться пробелами.
https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements
3. Предпочтительный способ работы с файлами использование конструкции with ... as. Пример:
```python
with open('books.csv') as csv_file:
```
4. В программе названия переменных должны иметь смысл, название отражает суть того, что содержит переменная. Отсюда применение переменных с названиями `q, a, h, s, f, cnt` ... недопустимо. Например, вместо `cnt` используем `long_names_num`, а `q` -> `book_field`
5. Зачем вы делаете `f.readline()` внутри цикла? Внутри цикла `for s in f:` переменная s уже содержит саму строку. Поэтому делать readline не нужно.
6.  Зачем вам вообще нужен список `a`? Вы и так итерируетесь по строкам файла в цикле `for s in f:`. Делайте проверку в нем.  `for i in range(len(a)-1):` не нужен. 
7. Такие записи `a[i][0]`, `spisok[i][6][6:10]` лучше разбивать на несколько инструкций для улучшения читаемости кода. А записи q[1] именовать нормально. Например:
```python
random_book = books[r]
author = random_book[3]
title = random_book[1]
date = random_book[6]
file.write(f'{r}, Автор - {author}, Книга - {title}, дата: {date}\n')
```
8. Не используйте транслит в названиях переменных. Это ухудшает читаемость. `vvod` --> `author_filter` и тд.
9. Используйте `f-строки`, это более предпочтительнее чем конкатенация (сложение), `print('dfsdfs', 'fdsfsd')` или несколько идущие подряд `print`
```python
print(f'Кол-во записей: {entries_num}')
```
10. По PEP8 длина строки должна быть не больше 79 символов.
11. Программа работает неверно. Условие ` (vvod == spisok[i][3]) or (vvod == spisok[i][4]) and int(spisok[i][6][6:10])<2016` работает неверно. Ниже в ответах объясните почему. Подсказка -- ознакомьтесь с приоритетами выполнения операций https://docs.python.org/3/reference/expressions.html#operator-precedence
![Снимок экрана от 2023-10-16 22-58-34](https://github.com/Kerpee/Lab1/assets/8919470/d8368225-7a78-49bd-90be-289508120fb8)
12. Не используйте магические числа (типа 2, 30, 21 и тд) в программе, суть которых понятна только вам. Обозначайте их как константы. Константы обычно указываются вначале программы после блока импортов. Пример:
```python
import csv

MAX_NAME = 30
```

**Comment by Kerpee** [comment]
Добрый день! Постарался учесть все замечания.
Ответ на 11 пункт: Операции "and"  имеет более высокий приоритет чем операция "or",т.е. изначально проверялось данное выражение ` (vvod == spisok[i][4]) and int(spisok[i][6][6:10])<2016 `, а потом уже проверялось оставшаяся часть ` (vvod == spisok[i][3]) or`, следовательно был не важен год написания книги, т.к. проверялся только автор.

**Comment by Kerpee** [comment]
Добрый день! Постарался учесть все замечания.
Ответ на 11 пункт: Операции "and" имеет более высокий приоритет чем операция "or",т.е. изначально проверялось данное выражение `(vvod == spisok[i][4]) and int(spisok[i][6][6:10])<2016,` а потом уже проверялось оставшаяся часть  `(vvod == spisok[i][3]) or,` следовательно был не важен год написания книги, т.к. проверялся только автор.
